
Vagrant.configure("2") do |config|

  # Script em variável
  $script_mysql = <<-SCRIPT
    sudo apt-get update && \
    sudo apt-get install -y mysql-server && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
  SCRIPT
  
  # Indica o box que será usado:
  config.vm.box = "alvistack/ubuntu-22.04"

  config.vm.define "mysqldb" do |mysql| # Bloco do mysql, agora todo o código pertence a ele

    # Port forwarding
    # mysql.vm.network "forwarded_port", guest: 80, host: 8080

    # PRIVATE NETWORK
    # Define um IP em BRIDGE para a máquina:
    # ip: <ip> -> Define IP estático
    # type: "dhcp" -> IP dinâmico
    ### config.vm.network "private_network", type: "dhcp"

    # PUBLIC NETWORK
    mysql.vm.network "public_network", ip: "192.168.15.50"

    # Shell Provisioner -> Executa comandos de forma automatizada
    mysql.vm.provision "shell", inline: "cat /configs/idUbuntu.pub >> .ssh/authorized_keys"
    mysql.vm.provision "shell", inline: $script_mysql

    # Seta configuração do MySQL
    mysql.vm.provision "shell", inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    mysql.vm.provision "shell", inline: "service mysql restart"

    # Synced Folder -> Torna pastas compartilhaveis 
    mysql.vm.synced_folder "./configs", "/configs"
    mysql.vm.synced_folder ".", "/vagrant", disable: true

  end

  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.network "forwarded_port", guest: 80, host: 8081
    phpweb.vm.network "public_network", ip: "192.168.15.51"

    phpweb.vm.box = "apache"
  end
end
